export enum Routes {
  Home = '/',
  Dashboard = '/dashboard',
  Accounts = '/accounts',
  Rebate = '/rebate',
  Withdrawal = '/withdrawal',
  Referrals = '/referrals',
  Admin = '/admin',
  AdminUsers = '/admin/users',
  AdminBrokerAccounts = '/admin/broker-accounts',
  AdminWithdrawals = '/admin/withdrawals',
  AdminRebate = '/admin/rebate',
  AdminConfig = '/admin/config',
  AdminAuditLog = '/admin/audit-log',
  Profile = '/profile',
  Faq = '/faq',
  Blog = '/blog',
}
